config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources 'aims'
  resources 'books'
  resources 'subscriptions'
  resources 'mobile_contracts'
  resources 'house_contracts'
  resources 'competitors'
  resources 'categories'

  namespace :api, { format: 'json' } do
    resources 'aims'
    resources 'future_aims'
    resources 'books'
    resources 'subscriptions'
    resources 'mobile_contracts'
    resources 'house_contracts'
    resources 'competitors'
    resources 'categories'
    resources 'todos'
  end
end

app/models/aim.rb
class Aim < ApplicationRecord
  validates :title, presence: true
  validates :reason, presence: true
  validates :advantage, presence: true
  validate :ended_at_validation
  has_many :aim_categories
  has_many :categories, through: :aim_categories
  belongs_to :future_aim, optional: true
  enum difficulty: { middle: 0, low: 1, high: 2 }
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/aim_category.rb
class AimCategory < ApplicationRecord
  belongs_to :aim
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :amount, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :aim_categories
  has_many :aims, through: :aim_categories
end

app/models/competitor.rb
class Competitor < ApplicationRecord
end

app/models/future_aim.rb
class FutureAim < ApplicationRecord
  has_many :aims
end

app/models/house_contract.rb
class HouseContract < ApplicationRecord
end

app/models/ideal_shape.rb
class IdealShape < ApplicationRecord
end

app/models/mobile_contract.rb
class MobileContract < ApplicationRecord
  validates :company_name, presence: true
  validates :month_cost, presence: true
  validates :contract_detail, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true
  validates :month_cost, presence: true
  enum importance: { low: 0, middle: 1, high: 2 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  enum status: { waiting: 0, doing: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private
      def user_params_from_auth_hash(auth_hash)
        {
          name: auth_hash.info.name,
          email: auth_hash.info.email,
          image: auth_hash.info.image,
        }
      end
  end
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController
  before_action :set_aim, only: [:show, :edit, :update, :destroy]

  def index
    @q = Aim.ransack(params[:q])
    @aims = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @aim = Aim.new
  end

  def create
    @aim = Aim.new(aim_params)
    if @aim.save
      flash[:success] = '目標を作成しました'
      redirect_to aims_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @aim.update(aim_params)
      flash[:success] = '目標を更新しました'
      redirect_to aim_path(@aim.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @aim.destroy
    flash[:success] = '目標を削除しました'
    redirect_to aims_path
  end

  private
    def set_aim
      @aim = Aim.find(params[:id])
    end

    def aim_params
      params.require(:aim).permit(:title, :reason, :advantage, :difficulty, :started_at, :ended_at, { category_ids: [] })
    end
end

app/controllers/api/aims_controller.rb
module Api
  class AimsController < ApplicationController
    before_action :set_aim, only: [:show, :edit, :update, :destroy]

    def index
      @aims = Aim.all
    end

    def show
    end

    def new
      @aim = Aim.new
    end

    def create
      @aim = Aim.new(aim_params)
      if @aim.save
        render json: @document, status: :ok
      else
        render json: { errors: @document.errors }, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
      def set_aim
        @aim = Aim.find(params[:id])
      end

      def aim_params
        params.require(:aim).permit(:title, :reason, :advantage, :genre, :difficulty, :started_at, :ended_at, { category_ids: [] })
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = '本を作成しました'
      redirect_to books_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:success] = '本を更新しました'
      redirect_to book_path(@book.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    flash[:success] = '本を削除しました'
    redirect_to books_path
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :amount, :is_library, :bought_at, :started_at, :ended_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_logged_in, only: :index

  def index
  end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/competitors_helper.rb
module CompetitorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
    def current_user
      return unless (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end

    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end

app/views/aims/_form.html.erb
<%= form_with(model: @aim, local: true) do |f| %>
  <%= render "shared/error_messages", model: @aim %>
  <div class="form-group mb-3">
    <%= f.label :title, '目標名', class: 'form-label background-color' %>
    <%= f.text_field :title, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :reason, '理由', class: 'form-label background-color' %>
    <%= f.text_area :reason, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :advantage, '得られるもの', class: 'form-label background-color' %>
    <%= f.text_area :advantage, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |c| %>
     <%=  c.label { c.check_box + c.text} %>
    <% end %>
  </div>


  <div class="form-group mb-3">
    <%= f.label :difficulty, '難易度', class: 'form-label background-color' %>
    <%= f.text_field :difficulty, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :started_at, '開始日時', class: 'form-label background-color' %>
    <%= f.datetime_field :started_at, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :ended_at, '終了日時', class: 'form-label background-color' %>
    <%= f.datetime_field :ended_at, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <% if action==='show' %>
      <%= link_to '編集', edit_aim_path(@aim.id), class: 'btn btn-primary' %>
    <% else %>
      <%= f.submit "#{ @aim.new_record? ? '新規作成' : '更新' }", class: 'mt-3 btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/aims/edit.html.erb
<% provide(:title, t('title.aim.edit')) %>
<h3 class="mt-3 text-center"><%= t('title.aim.edit')%></h3>
<%= render partial: 'form', locals: { action: 'edit' } %>

app/views/aims/index.html.erb
<% provide(:title, t('title.aim.index')) %>
<h3 class="mt-3 text-center"><%= t('title.aim.index')%></h3>

<div class="d-flex justify-content-end">
  <%= link_to "新規作成", new_aim_path, class: 'mb-3 btn btn-primary' %>
</div>

<%= search_form_for @q, class: 'row g-3', url: aims_path do |f| %>
  <div class="col-md-4">
    <%= f.label :title_cont, '目標名', class: 'form-label' %>
    <%= f.search_field :title_cont, class: 'form-control' %>

    <%= f.label :categories_id_in, 'カテゴリー', class: 'form-label' %>
    <%= f.collection_check_boxes :categories_id_in, Category.all, :id, :name, {}, class: 'mx-1' %>

    <br>
    <%= f.label :started_at_gteq, '開始日時', class: 'form-label' %>
    <%= f.datetime_field :started_at_gteq, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= f.label :reason_cont, '理由', class: 'form-label' %>
    <%= f.text_area :reason_cont, class: 'form-control' %>

    <%= f.label :ended_at_lteq, '終了日時', class: 'form-label' %>
    <%= f.datetime_field :ended_at_lteq, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= f.label :advantage_cont, '得られるもの', class: 'form-label' %>
    <%= f.text_area :advantage_cont, class: 'form-control' %>

    <%= f.label :difficulty_cont, '難易度', class: 'form-label' %>
    <%= f.search_field :difficulty_cont, class: 'form-control' %>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <%= f.submit "クリア", type: :reset, class: 'btn btn-light' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="mt-3 table table-bordered">
  <tr>
    <th><%= sort_link(@q, :title, '目標名', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :reason, '理由', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :advantage, '利点', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :difficulty, '難易度', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :started_at, '開始日時', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :ended_at, '終了日時', class: 'nav-link') %></th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  
  <% @aims.each do |aim| %>
    <tr>
      <td><%= link_to aim.title, aim_path(aim), class: 'nav-link' %></td>
      <td><%= aim.reason %></td>
      <td><%= aim.advantage %></td>
      <td><%= t("enum.aim.difficulty.#{aim.difficulty}") %></td>
      <td><%= aim.started_at %></td>
      <td><%= aim.ended_at %></td>
      <td><%= link_to '編集', edit_aim_path(aim.id), class: 'btn btn-primary' %></td>
      <td><%= button_to '削除', aim_path(aim.id), method: :delete, form:{ data: { turbo_confirm: "目標を削除します。よろしいですか？" }}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= paginate @aims %>

app/views/aims/new.html.erb
<% provide(:title, t('title.aim.new')) %>
<h3 class="mt-3 text-center"><%= t('title.aim.new')%></h3>
<%= render partial: 'form', locals: { action: 'new' } %>

app/views/aims/show.html.erb
<% provide(:title, t('title.aim.show')) %>
<h3 class="mt-3 text-center"><%= t('title.aim.show')%></h3>
<%= render partial: 'form', locals: { action: 'show' } %>