config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources 'aims'
  resources 'books'
  resources 'subscriptions'
  resources 'mobile_contracts'
  resources 'house_contracts'
  resources 'competitors'
  resources 'categories'

  namespace :api, { format: 'json' } do
    resources 'aims'
    resources 'future_aims'
    resources 'books'
    resources 'subscriptions'
    resources 'mobile_contracts'
    resources 'house_contracts'
    resources 'competitors'
    resources 'categories'
    resources 'todos'
  end
end

app/models/aim.rb
class Aim < ApplicationRecord
  validates :title, presence: true
  validates :reason, presence: true
  validates :advantage, presence: true
  validate :ended_at_validation
  has_many :aim_categories
  has_many :categories, through: :aim_categories
  belongs_to :future_aim, optional: true
  enum difficulty: { middle: 0, low: 1, high: 2 }
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/aim_category.rb
class AimCategory < ApplicationRecord
  belongs_to :aim
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :amount, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :aim_categories
  has_many :aims, through: :aim_categories
end

app/models/competitor.rb
class Competitor < ApplicationRecord
end

app/models/future_aim.rb
class FutureAim < ApplicationRecord
  has_many :aims
end

app/models/house_contract.rb
class HouseContract < ApplicationRecord
end

app/models/ideal_shape.rb
class IdealShape < ApplicationRecord
end

app/models/mobile_contract.rb
class MobileContract < ApplicationRecord
  validates :company_name, presence: true
  validates :month_cost, presence: true
  validates :contract_detail, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true
  validates :month_cost, presence: true
  enum importance: { low: 0, middle: 1, high: 2 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  enum status: { waiting: 0, doing: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private
      def user_params_from_auth_hash(auth_hash)
        {
          name: auth_hash.info.name,
          email: auth_hash.info.email,
          image: auth_hash.info.image,
        }
      end
  end
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController
  before_action :set_aim, only: [:show, :edit, :update, :destroy]

  def index
    @q = Aim.ransack(params[:q])
    @aims = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @aim = Aim.new
  end

  def create
    @aim = Aim.new(aim_params)
    if @aim.save
      flash[:success] = '目標を作成しました'
      redirect_to aims_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @aim.update(aim_params)
      flash[:success] = '目標を更新しました'
      redirect_to aim_path(@aim.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @aim.destroy
    flash[:success] = '目標を削除しました'
    redirect_to aims_path
  end

  private
    def set_aim
      @aim = Aim.find(params[:id])
    end

    def aim_params
      params.require(:aim).permit(:title, :reason, :advantage, :difficulty, :started_at, :ended_at, { category_ids: [] })
    end
end

app/controllers/api/subscriptions_controller.rb
module Api
  class SubscriptionsController < ApplicationController
    before_action :set_subscription, only: [:show, :edit, :update, :destroy]

    def index
      @subscriptions = Subscription.all
      total = 0
      @subscriptions.each do |f|
        total = total + f.month_cost
      end
      @total = total
    end

    def show
    end

    def new
      @subscription = Subscription.new
    end

    def create
      @subscription = Subscription.new(subscription_params)
      if @subscription.save
        render json: @document, status: :ok
      else
        render json: { errors: @document.errors }, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
      def set_subscription
        @subscription = Subscription.find(params[:id])
      end

      def subscription_params
        params.require(:subscription).permit(:name, :month_cost, :importance, :alternative)
      end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  def index
    @q = Subscription.ransack(params[:q])
    @subscriptions = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      flash[:success] = 'サブスクリプションを作成しました'
      redirect_to subscriptions_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @subscription.update(subscription_params)
      flash[:success] = 'サブスクリプションを更新しました'
      redirect_to subscription_path(@subscription.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @subscription.destroy
    flash[:success] = 'サブスクリプションを削除しました'
    redirect_to subscriptions_path
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:name, :month_cost, :importance, :alternative)
    end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/competitors_helper.rb
module CompetitorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
    def current_user
      return unless (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end

    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: @subscription, local: true) do |f| %>
    <%= render "shared/error_messages", model: @subscription %>
    <div class="form-group mb-3">
      <%= f.label :name, 'サブスクリプション名', class: 'form-label background-color' %>
      <%= f.text_field :name, class: 'form-control', readonly: action==='show' %>
    </div>
  
    <div class="form-group mb-3">
      <%= f.label :month_cost, '月額料金', class: 'form-label background-color' %>
      <%= f.number_field :month_cost, class: 'form-control', readonly: action==='show' %>
    </div>
  
    <div class="form-group mb-3">
      <%= f.label :importance, '重要性', class: 'form-label background-color' %>
      <%= f.text_field :importance, class: 'form-control', readonly: action==='show' %>
    </div>
  
    <div class="form-group mb-3">
      <%= f.label :alternative, '代替手段', class: 'form-label background-color' %>
      <%= f.text_area :alternative, class: 'form-control', readonly: action==='show' %>
    </div>
  
    <div class="form-group mb-3">
      <% if action==='show' %>
        <%= link_to '編集', edit_subscription_path(@subscription.id), class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit "#{ @subscription.new_record? ? '新規作成' : '更新' }", class: 'mt-3 btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
  

app/views/subscriptions/edit.html.erb
<% provide(:title, t('title.subscription.edit')) %>
<h3 class="mt-3 text-center"><%= t('title.subscription.edit')%></h3>
<%= render partial: 'form', locals: { action: 'edit' } %>

app/views/subscriptions/index.html.erb
<% provide(:title, t('title.subscription.index')) %>
<h3 class="mt-3 text-center"><%= t('title.subscription.index')%></h3>

<div class="d-flex justify-content-end">
  <%= link_to "新規作成", new_subscription_path, class: 'mb-3 btn btn-primary' %>
</div>

<%= search_form_for @q, class: 'row g-3', url: subscriptions_path do |f| %>
  <div class="col-md-4">
    <%= f.label :name_cont, 'サブスクリプション名', class: 'form-label' %>
    <%= f.search_field :name_cont, class: 'form-control' %>
    
    <%= f.label :month_cost_cont, '月額料金', class: 'form-label' %>
    <%= f.search_field :month_cost_cont, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= f.label :importance_cont, '重要性', class: 'form-label' %>
    <%= f.number_field :importance_cont, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= f.label :alternative_cont, '代替手段', class: 'form-label' %>
    <%= f.text_area :alternative_cont, class: 'form-control' %>
  </div>

  <div class="d-flex justify-content-center mb-3">
    <%= f.submit "クリア", type: :reset, class: 'btn btn-light' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="mt-3 table table-bordered">
  <tr>
    <th><%= sort_link(@q, :name, 'サブスクリプション名', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :month_cost, '月額料金', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :importance, '重要性', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :alternative, '代替手段', class: 'nav-link') %></th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  
  <% @subscriptions.each do |subscription| %>
    <tr>
      <td><%= link_to subscription.name, subscription_path(subscription), class: 'nav-link' %></td>
      <td><%= subscription.month_cost %></td>
      <td><%= subscription.importance %></td>
      <td><%= subscription.alternative %></td>
      <td><%= link_to '編集', edit_subscription_path(subscription.id), class: 'btn btn-primary' %></td>
      <td><%= button_to '削除', subscription_path(subscription.id), method: :delete, form: { data: { turbo_confirm: "サブスクリプションを削除します。よろしいですか？" }}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= paginate @subscriptions %>

app/views/subscriptions/new.html.erb
<% provide(:title, t('title.subscription.new')) %>
<h3 class="mt-3 text-center"><%= t('title.subscription.new')%></h3>
<%= render partial: 'form', locals: { action: 'new' } %>

app/views/subscriptions/show.html.erb
<% provide(:title, t('title.subscription.show')) %>
<h3 class="mt-3 text-center"><%= t('title.subscription.show')%></h3>
<%= render partial: 'form', locals: { action: 'show' } %>