config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources 'aims'
  resources 'books'
  resources 'subscriptions'
  resources 'mobile_contracts'
  resources 'house_contracts'
  resources 'competitors'
  resources 'categories'

  namespace :api, { format: 'json' } do
    resources 'aims'
    resources 'future_aims'
    resources 'books'
    resources 'subscriptions'
    resources 'mobile_contracts'
    resources 'house_contracts'
    resources 'competitors'
    resources 'categories'
    resources 'todos'
  end
end

app/models/aim.rb
class Aim < ApplicationRecord
  validates :title, presence: true
  validates :reason, presence: true
  validates :advantage, presence: true
  validate :ended_at_validation
  has_many :aim_categories
  has_many :categories, through: :aim_categories
  belongs_to :future_aim, optional: true
  enum difficulty: { middle: 0, low: 1, high: 2 }
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/aim_category.rb
class AimCategory < ApplicationRecord
  belongs_to :aim
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :amount, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :aim_categories
  has_many :aims, through: :aim_categories
end

app/models/competitor.rb
class Competitor < ApplicationRecord
end

app/models/future_aim.rb
class FutureAim < ApplicationRecord
  has_many :aims
end

app/models/house_contract.rb
class HouseContract < ApplicationRecord
end

app/models/ideal_shape.rb
class IdealShape < ApplicationRecord
end

app/models/mobile_contract.rb
class MobileContract < ApplicationRecord
  validates :company_name, presence: true
  validates :month_cost, presence: true
  validates :contract_detail, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true
  validates :month_cost, presence: true
  enum importance: { low: 0, middle: 1, high: 2 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  enum status: { waiting: 0, doing: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private
      def user_params_from_auth_hash(auth_hash)
        {
          name: auth_hash.info.name,
          email: auth_hash.info.email,
          image: auth_hash.info.image,
        }
      end
  end
end

app/controllers/aims_controller.rb
class AimsController < ApplicationController
  before_action :set_aim, only: [:show, :edit, :update, :destroy]

  def index
    @q = Aim.ransack(params[:q])
    @aims = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @aim = Aim.new
  end

  def create
    @aim = Aim.new(aim_params)
    if @aim.save
      flash[:success] = '目標を作成しました'
      redirect_to aims_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @aim.update(aim_params)
      flash[:success] = '目標を更新しました'
      redirect_to aim_path(@aim.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @aim.destroy
    flash[:success] = '目標を削除しました'
    redirect_to aims_path
  end

  private
    def set_aim
      @aim = Aim.find(params[:id])
    end

    def aim_params
      params.require(:aim).permit(:title, :reason, :advantage, :difficulty, :started_at, :ended_at, { category_ids: [] })
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @q = Category.ransack(params[:q])
    @categories = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'カテゴリーを作成しました'
      redirect_to categories_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = 'カテゴリーを更新しました'
      redirect_to category_path(@category.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    flash[:success] = 'カテゴリーを削除しました'
    redirect_to categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_logged_in, only: :index

  def index
  end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/competitors_helper.rb
module CompetitorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
    def current_user
      return unless (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end

    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
    <%= render "shared/error_messages", model: @category %>
    <div class="form-group mb-3">
      <%= f.label :name, 'カテゴリー名', class: 'form-label background-color' %>
      <%= f.text_field :name, class: 'form-control', readonly: action==='show' %>
    </div>
  
    <div class="form-group mb-3">
      <% if action==='show' %>
        <%= link_to '編集', edit_category_path(@category.id), class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit "#{ @category.new_record? ? '新規作成' : '更新' }", class: 'mt-3 btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
  

app/views/categories/edit.html.erb
<% provide(:title, t('title.category.edit')) %>
<h3 class="mt-3 text-center"><%= t('title.category.edit')%></h3>
<%= render partial: 'form', locals: { action: 'edit' } %>

app/views/categories/index.html.erb
<% provide(:title, t('title.category.index')) %>
<h3 class="mt-3 text-center"><%= t('title.category.index')%></h3>

<div class="d-flex justify-content-end">
  <%= link_to "新規作成", new_category_path, class: 'mb-3 btn btn-primary' %>
</div>

<%= search_form_for @q, class: 'row g-3', url: categories_path do |f| %>
  <div class="col-md-4">
    <%= f.label :name_cont, 'カテゴリー名', class: 'form-label' %>
    <%= f.search_field :name_cont, class: 'form-control' %>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <%= f.submit "クリア", type: :reset, class: 'btn btn-light' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="mt-3 table table-bordered">
  <tr>
    <th><%= sort_link(@q, :name, 'カテゴリー名', class: 'nav-link') %></th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category), class: 'nav-link' %></td>
      <td><%= link_to '編集', edit_category_path(category.id), class: 'btn btn-primary' %></td>
      <td><%= button_to '削除', category_path(category.id), method: :delete, form:{ data: { turbo_confirm: "目標を削除します。よろしいですか？" }}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= paginate @categories %>

app/views/categories/new.html.erb
<% provide(:title, t('title.category.new')) %>
<h3 class="mt-3 text-center"><%= t('title.category.new')%></h3>
<%= render partial: 'form', locals: { action: 'new' } %>

app/views/categories/show.html.erb
<% provide(:title, t('title.category.show')) %>
<h3 class="mt-3 text-center"><%= t('title.category.show')%></h3>
<%= render partial: 'form', locals: { action: 'show' } %>