config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources 'aims'
  resources 'books'
  resources 'subscriptions'
  resources 'mobile_contracts'
  resources 'house_contracts'
  resources 'competitors'
  resources 'categories'

  namespace :api, { format: 'json' } do
    resources 'aims'
    resources 'future_aims'
    resources 'books'
    resources 'subscriptions'
    resources 'mobile_contracts'
    resources 'house_contracts'
    resources 'competitors'
    resources 'categories'
    resources 'todos'
  end
end

app/models/aim.rb
class Aim < ApplicationRecord
  validates :title, presence: true
  validates :reason, presence: true
  validates :advantage, presence: true
  validate :ended_at_validation
  has_many :aim_categories
  has_many :categories, through: :aim_categories
  belongs_to :future_aim, optional: true
  enum difficulty: { middle: 0, low: 1, high: 2 }
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/aim_category.rb
class AimCategory < ApplicationRecord
  belongs_to :aim
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :amount, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :aim_categories
  has_many :aims, through: :aim_categories
end

app/models/competitor.rb
class Competitor < ApplicationRecord
end

app/models/future_aim.rb
class FutureAim < ApplicationRecord
  has_many :aims
end

app/models/house_contract.rb
class HouseContract < ApplicationRecord
end

app/models/ideal_shape.rb
class IdealShape < ApplicationRecord
end

app/models/mobile_contract.rb
class MobileContract < ApplicationRecord
  validates :company_name, presence: true
  validates :month_cost, presence: true
  validates :contract_detail, presence: true
  validate :ended_at_validation
end

def ended_at_validation
  errors.add(:ended_at, '終了日時は開始日時よりも後を設定してください') if started_at.present? && ended_at.present? && started_at > ended_at
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true
  validates :month_cost, presence: true
  enum importance: { low: 0, middle: 1, high: 2 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  enum status: { waiting: 0, doing: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private
      def user_params_from_auth_hash(auth_hash)
        {
          name: auth_hash.info.name,
          email: auth_hash.info.email,
          image: auth_hash.info.image,
        }
      end
  end
end

app/helpers/aims_helper.rb
module AimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/competitors_helper.rb
module CompetitorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper
    def current_user
      return unless (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end

    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <%= link_to "ホーム", aims_path, class: "nav-link" %>
        <nav>
          <div class="nav navbar-nav navbar-right">
            <% if current_user %>
              <% if current_user.image %>
                <%= image_tag current_user.image %>
              <% end %>
              <%= current_user.name %>さん
              <%= link_to "ログアウト", log_out_path, class: "nav-link" %>
            <% else  %>
              <li class="navbar">
                ゲストさん
              </li>
              <li class="navbar">
                <%= button_to "ログイン", "/login", method: :get, data: { turbo: false }, class: "btn btn-primary" %>
              </li>
              <li class="navbar">
                <%= button_to "Googleでログイン", "/auth/google_oauth2", method: :post, data: { turbo: false }, class: "btn btn-secondary" %>
              </li>
            <% end %>
          </div>
        </nav>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-2">
          <ul class="mt-3 navbar-nav">
            <li class="nav-item"><%= link_to "目標一覧", aims_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "書籍一覧", books_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "カテゴリー一覧", categories_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "サブスクリプション一覧", subscriptions_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "スマホ契約一覧", mobile_contracts_path, class: "nav-link" %></li>
          </ul>
        </div>
        <div class="col-10">
          <% flash.each do |status, message| %>
            <div>
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>